import { QuestionnaireData } from './types';

/* ─────────────────── Label Lookups ─────────────────── */

const platformLabel: Record<string, string> = {
  nextjs: 'Next.js / React App',
  wordpress: 'WordPress',
  shopify: 'Shopify',
  custom: 'Custom Stack',
};

const styleLabel: Record<string, string> = {
  minimalist: 'Clean & Minimalist',
  colorful: 'Vibrant & Playful',
  corporate: 'Sleek & Professional',
  bold: 'Modern & Bold',
};

const budgetLabel: Record<string, string> = {
  'under-5k': 'Under $5,000',
  '5k-15k': '$5,000 – $15,000',
  '15k-30k': '$15,000 – $30,000',
  'over-30k': '$30,000+',
};

const timelineLabel: Record<string, string> = {
  '1-month': 'Within 1 month',
  '1-3-months': '1–3 months',
  '3-6-months': '3–6 months',
  flexible: 'Flexible',
};

const featureLabel: Record<string, string> = {
  auth: 'User Authentication & Profiles',
  payments: 'E-commerce & Payments',
  cms: 'Content Management System',
  integrations: 'Third-party API Integrations',
  search: 'Advanced Search & Filters',
  analytics: 'Analytics & Reporting',
  multilingual: 'Multi-language Support',
  realtime: 'Real-time Features',
};

const trafficLabel: Record<string, string> = {
  'under-10k': 'Under 10,000 / month',
  '10k-100k': '10,000 – 100,000 / month',
  '100k-1m': '100,000 – 1,000,000 / month',
  'over-1m': 'Over 1,000,000 / month',
  unsure: 'Not sure yet',
};

const contentProviderLabel: Record<string, string> = {
  client: 'Client-provided',
  developer: 'Developer-created',
  collab: 'Collaborative',
};

const label = (map: Record<string, string>, key: string): string =>
  map[key] || key;

/* ─────────────────── Project Brief ─────────────────── */

export const generateMarkdownBrief = (data: QuestionnaireData): string => {
  const d = data;
  const sections: string[] = [];

  // Header
  sections.push(
    `# Project Brief: ${d.overview.projectName || 'Untitled Project'}`,
    `Generated by **Client Brief AI** on ${new Date().toLocaleDateString()}`,
    '---',
  );

  // 1. Project Overview
  sections.push(`## 1. Project Overview`);
  sections.push(`* **Project Name:** ${d.overview.projectName}`);
  sections.push(`* **Client:** ${d.overview.clientName}`);
  sections.push(`* **Email:** ${d.overview.clientEmail}`);
  sections.push(`* **Platform:** ${label(platformLabel, d.technical.platform)}`);
  sections.push(`* **Budget:** ${label(budgetLabel, d.scope.budget)}`);
  sections.push(`* **Timeline:** ${label(timelineLabel, d.scope.timeline)}`);
  sections.push(`* **Expected Traffic:** ${label(trafficLabel, d.technical.traffic)}`);
  sections.push(`* **Content Provider:** ${label(contentProviderLabel, d.scope.contentProvider)}`);
  sections.push('');

  // Business Details & Goals
  sections.push(`### Business Overview`);
  sections.push(d.overview.businessDescription || 'Not Specified');
  sections.push('');
  sections.push(`### Project Goals & Problem Solved`);
  sections.push(`* **Primary Goal:** ${d.technical.primaryGoal || 'Not Specified'}`);
  sections.push(`* **Problem Addressed:** ${d.overview.projectProblem || 'Not Specified'}`);
  sections.push(`* **Key Action / CTA:** ${d.technical.visitorAction || 'Not Specified'}`);
  sections.push(`* **Target Audience:** ${d.overview.targetAudience || 'Not Specified'}`);
  sections.push('');
  sections.push(`### Detailed Description`);
  sections.push(d.overview.projectDescription || 'Not Specified');

  // 2. Pages & Features
  sections.push('', '---', '');
  sections.push(`## 2. Pages & Features`);
  sections.push(`### Requested Pages`);
  sections.push(d.technical.neededPages || 'Not Specified');
  sections.push('');
  sections.push(`### Core Features Checklist`);
  if (d.technical.features.length > 0) {
    d.technical.features.forEach((f) => {
      sections.push(`* [x] ${label(featureLabel, f)}`);
    });
  } else {
    sections.push('* No specific features selected from checklist.');
  }
  sections.push('');
  sections.push(`### Custom Features List`);
  sections.push(d.technical.importantFeatures || 'Not Specified');

  // 3. Design Preferences
  sections.push('', '---', '');
  sections.push(`## 3. Design Preferences`);
  sections.push(`* **Style:** ${label(styleLabel, d.design.style)}`);
  sections.push(`* **Brand Guidelines:** ${d.design.hasGuidelines ? 'Yes – client has existing guidelines' : 'No – guidelines need to be created'}`);
  if (d.design.competitors && d.design.competitors.trim()) {
    sections.push(`* **Inspirations / Competitors:**`);
    sections.push(`  ${d.design.competitors.replace(/\n/g, '\n  ')}`);
  }
  if (d.design.likedWebsites && d.design.likedWebsites.trim()) {
    sections.push(`* **Liked Websites & Design References:**`);
    sections.push(`  ${d.design.likedWebsites.replace(/\n/g, '\n  ')}`);
  }

  // 4. Additional Notes (only if provided)
  if (d.scope.notes && d.scope.notes.trim()) {
    sections.push('', '---', '');
    sections.push(`## 4. Additional Notes`);
    sections.push(d.scope.notes);
  }

  return sections.join('\n');
};

/* ─────────────────── AI Development Prompt ─────────────────── */

export const generateAIPrompt = (data: QuestionnaireData): string => {
  const d = data;
  const lines: string[] = [];

  lines.push(`You are a senior full-stack developer. Build the project described below using ONLY the requirements listed. Do not add features, pages, integrations, or design elements that are not explicitly specified.`);
  lines.push('');

  // 1. Project Overview & Business Requirements
  lines.push('### PROJECT OVERVIEW & BUSINESS');
  lines.push(`- Project Name: ${d.overview.projectName}`);
  lines.push(`- Client: ${d.overview.clientName} (${d.overview.clientEmail})`);
  lines.push(`- Business Details: ${d.overview.businessDescription || 'Not Specified'}`);
  lines.push(`- Problem Solved: ${d.overview.projectProblem || 'Not Specified'}`);
  lines.push(`- Primary Goal: ${d.technical.primaryGoal || 'Not Specified'}`);
  lines.push(`- Primary Call to Action: ${d.technical.visitorAction || 'Not Specified'}`);
  lines.push(`- Target Audience: ${d.overview.targetAudience || 'Not Specified'}`);
  lines.push(`- Description: ${d.overview.projectDescription}`);
  lines.push('');

  // 2. Pages Structure
  lines.push('### PAGES STRUCTURE');
  lines.push(d.technical.neededPages || 'Not Specified');
  lines.push('');

  // 3. Platform & Tech Stack
  lines.push('### PLATFORM & TECH STACK');
  lines.push(`- Preferred platform: ${label(platformLabel, d.technical.platform)}`);
  lines.push('');

  // 4. Features
  lines.push('### FEATURES LIST');
  lines.push('#### Checklist Features:');
  if (d.technical.features.length > 0) {
    d.technical.features.forEach((f) => {
      lines.push(`- ${label(featureLabel, f)}`);
    });
  } else {
    lines.push('- No specific checklist features selected.');
  }
  lines.push('');
  lines.push('#### Additional Required Features:');
  lines.push(d.technical.importantFeatures || 'Not Specified');
  lines.push('');

  // 5. Design
  lines.push('### DESIGN REQUIREMENTS');
  lines.push(`- Visual style: ${label(styleLabel, d.design.style)}`);
  lines.push(`- Brand guidelines available: ${d.design.hasGuidelines ? 'Yes' : 'No'}`);
  if (d.design.competitors && d.design.competitors.trim()) {
    lines.push(`- Inspirations / competitors: ${d.design.competitors.replace(/\n/g, ', ')}`);
  }
  if (d.design.likedWebsites && d.design.likedWebsites.trim()) {
    lines.push(`- Liked websites & design references: ${d.design.likedWebsites.replace(/\n/g, ', ')}`);
  }
  lines.push('');

  // 6. Traffic & Scale
  lines.push('### TRAFFIC & SCALE');
  lines.push(`- Expected traffic: ${label(trafficLabel, d.technical.traffic)}`);
  lines.push('');

  // 7. Budget & Timeline
  lines.push('### BUDGET & TIMELINE');
  lines.push(`- Budget: ${label(budgetLabel, d.scope.budget)}`);
  lines.push(`- Timeline: ${label(timelineLabel, d.scope.timeline)}`);
  lines.push(`- Content provider: ${label(contentProviderLabel, d.scope.contentProvider)}`);
  lines.push('');

  // 8. Additional Notes (only if provided)
  if (d.scope.notes && d.scope.notes.trim()) {
    lines.push('### ADDITIONAL NOTES FROM CLIENT');
    lines.push(d.scope.notes);
    lines.push('');
  }

  // 9. Instructions
  lines.push('### DEVELOPMENT INSTRUCTIONS');
  lines.push('- Implement ONLY the features and pages listed above.');
  lines.push('- Do NOT invent pages, features, integrations, or business logic not described here.');
  lines.push('- Use TypeScript with strict types for all entities.');
  lines.push('- Implement form validation and proper error handling.');
  lines.push('- Ensure responsive design (mobile, tablet, desktop).');
  lines.push('- Write clean, production-ready code with clear file organization.');
  if (!d.design.hasGuidelines) {
    lines.push('- Since no brand guidelines exist, create a clean minimal UI that matches the selected visual style.');
  }

  return lines.join('\n');
};
